spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_db
    username: root      # MySQL 사용자 이름
    password: mysql      # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    initialize-schema: embedded
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

